[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine    = { path = "../engine" }
resources = { path = "../resources" }
serde = { path = "../../third_party/serde" }
math = { path = "../math" }
sync = { path = "../sync" }