[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

[lib]
path = "ecs.rs"

[dependencies]
engine    = { path = "../engine" }
resources = { path = "../resources" }
serde = { path = "../../third_party/serde" }
math = { path = "../math" }