[package]
name = "resources"
version = "0.0.0"
edition = "2021"

[lib]
path = "resources.rs"

[dependencies]
engine = { path = "../engine" }
cache = { path = "../cache" }
serde = { path = "../../third_party/serde"}

derive = { path = "../derive" }