[package]
name = "orchard"
version = "0.0.0"
edition = "2021"

[[bin]]
path = "orchard.rs"
name = "orchard"

[dependencies]
engine = { path = "../../runtime/engine" }
editor = { path = "../../runtime/editor" }

