[package]
name = "orchard"
version = "0.0.0"
edition = "2021"

[[bin]]
path = "orchard.rs"
name = "orchard"

[dependencies]
engine = { path = "../../runtime/engine" }
game = { path = "../../runtime/game" }
ecs = { path = "../../runtime/ecs" }
math = { path = "../../runtime/math" }
physics3d = { path = "../../runtime/physics3d" }
resources = { path = "../../runtime/resources" }
input = { path = "../../runtime/input" }
serde = { path = "../../third_party/serde" }
