[package]
name = "gpu"
version = "0.2.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/colbyhall/newport"
description = "Thread safe render abstraction layer for Newport engine"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[dependencies]
engine 		= { path = "../engine" }
platform 	= { path = "../platform" }
math   		= { path = "../math" }
resources 	= { path = "../resources" }

serde   	= { path = "../../third_party/serde" }
# aftermath   = { path = "../../third_party/aftermath" }

ash  = "0.32.0"
bitflags = "1.2"

hassle-rs = "0.5.2"
stb_image = "0.2.3"

[features]
default = ["vulkan"]
vulkan  = []