[package]
name = "physics2d"
version = "0.0.0"
edition = "2021"

[lib]
path = "physics2d.rs"

[dependencies]
engine = { path = "../engine" }
ecs = { path = "../ecs" }
math = { path = "../math" }
serde = { path = "../../third_party/serde" }

rapier2d = { version = "0.11", features = ["simd-stable", "serde-serialize"] }