[package]
name = "physics3d"
version = "0.0.0"
edition = "2021"

[lib]
path = "physics3d.rs"

[dependencies]
engine = { path = "../engine" }
ecs = { path = "../ecs" }
math = { path = "../math" }
game = { path = "../game" }
serde = { path = "../../third_party/serde" }

rapier3d = { version = "0.11", features = ["simd-stable", "serde-serialize"] }