[package]
name = "newport"
version = "0.0.1"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/colbyhall/newport"
description = "Fast module game engine built in rust"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[workspace]
members = ["crates/*"]

[dependencies]
newport_os        = { path = "crates/newport_os", version = "0.0.1" }
newport_asset     = { path = "crates/newport_asset", version = "0.0.1" }
newport_log       = { path = "crates/newport_log", version = "0.0.1" }
newport_engine    = { path = "crates/newport_engine", version = "0.0.1" }
newport_gpu       = { path = "crates/newport_gpu", version = "0.0.1" }
newport_graphics  = { path = "crates/newport_graphics", version = "0.0.1" }
newport_math      = { path = "crates/newport_math", version = "0.0.1" }
newport_editor    = { path = "crates/newport_editor", version = "0.0.1" }
newport_codegen   = { path = "crates/newport_codegen", version = "0.0.1" }
newport_ecs       = { path = "crates/newport_ecs", version = "0.0.1", features = ["editable"] }
newport_game      = { path = "crates/newport_game", version = "0.0.1" }
newport_imgui     = { path = "crates/newport_imgui", version = "0.0.1" }

# Serde sadly has to be included in the dependency list of every package that uses it
serde = { version = "1.0.125", features = ["derive"] }

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "game"
path = "examples/game.rs"

[[example]]
name = "levy"
path = "examples/levy.rs"

[[example]]
name = "imgui"
path = "examples/imgui.rs"

[profile.dev]
overflow-checks = false

[features]
default = ["editor"]
editor = ["newport_game/editor"]