[package]
name = "newport"
version = "0.2.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/colbyhall/newport"
description = "Modular Game Engine built in Rust"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[workspace]
members = ["crates/*"]

[dependencies]
newport_platform  = { path = "crates/newport_platform", version = "0.2.0" }
newport_asset     = { path = "crates/newport_asset", version = "0.2.0" }
newport_log       = { path = "crates/newport_log", version = "0.2.0" }
newport_engine    = { path = "crates/newport_engine", version = "0.2.0" }
newport_gpu       = { path = "crates/newport_gpu", version = "0.2.0" }
newport_graphics  = { path = "crates/newport_graphics", version = "0.2.0" }
newport_math      = { path = "crates/newport_math", version = "0.2.0" }
newport_ecs       = { path = "crates/newport_ecs", version = "0.2.0" }
newport_game      = { path = "crates/newport_game", version = "0.2.0" }
newport_imgui     = { path = "crates/newport_imgui", version = "0.2.0" }

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "game"
path = "examples/game.rs"

[[example]]
name = "gpu"
path = "examples/gpu.rs"

[[example]]
name = "imgui"
path = "examples/imgui.rs"

[profile.dev]
overflow-checks = false