[package]
name = "engine"
version = "0.0.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/colbyhall/newport"
description = "Core runnable library for the Newport engine"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[lib]
path = "engine.rs"

[dependencies]
os    = { path = "../os" }
math  = { path = "../math" }

serde = { path = "../../third_party/serde" }

toml      = "0.5"
getrandom = "0.2"