[package]
name = "platform"
version = "0.2.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/colbyhall/newport"
description = "Os abstractions for engine use"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[dependencies]
lazy_static = "1.4.0"
math = { path = "../math" }

winapi = { version = "0.3.9", features = ["winuser", "sysinfoapi", "impl-default"] }
winit = "0.25"
raw-window-handle = "0.3.3"