[package]
name = "game3d"
version = "0.0.0"
edition = "2021"

[lib]
path = "game3d.rs"

[dependencies]
engine = { path = "../engine" }
ecs = { path = "../ecs" }
math = { path = "../math" }
serde = { path = "../../third_party/serde" }
gpu = { path = "../gpu" }
draw2d = { path = "../draw2d" }
resources = { path = "../resources" }
input = { path = "../input" }

editor = { path = "../editor", optional = true }

gltf = "1.0"

[features]
default = []