[package]
name = "game3d"
version = "0.1.0"
edition = "2021"

[lib]
path = "game3d.rs"

[dependencies]
engine = { path = "../engine" }
ecs = { path = "../ecs" }
math = { path = "../math" }
serde = { path = "../../third_party/serde" }
gpu = { path = "../gpu" }
graphics = { path = "../graphics" }
resources = { path = "../resources" }

egui = { path = "../../third_party/egui", optional = true }

[features]
default = ["editor"]
editor = ["egui"]