[package]
name = "game2d"
version = "0.0.0"
edition = "2021"

[lib]
path = "game2d.rs"

[dependencies]
engine = { path = "../engine" }
ecs = { path = "../ecs" }
math = { path = "../math" }
gpu = { path = "../gpu" }
draw2d = { path = "../draw2d" }
resources = { path = "../resources" }
input = { path = "../input" }
config = { path = "../config" }

serde = { path = "../../third_party/serde" }