[package]
name = "os"
version = "0.0.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/colbyhall/newport"
description = "Os abstractions for engine use"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[lib]
path = "os.rs"

[dependencies]
math = { path = "../math" }
serde = { path = "../../third_party/serde" }

winapi = { version = "0.3.9", features = ["winuser", "sysinfoapi", "libloaderapi", "errhandlingapi", "impl-default"] }
winit = "0.26.1"
raw-window-handle = "0.4.2"