[package]
name = "graphics"
version = "0.2.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/colbyhall/newport"
description = "Graphics rendering library for Newport engine"
categories = ["game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "newport"]

[lib]
path = "graphics.rs"

[dependencies]
engine = { path = "../engine" }
gpu    = { path = "../gpu" }
math   = { path = "../math" }
resources  = { path = "../resources" }
serde  = { path = "../../third_party/serde" }

freetype-rs = "0.27.0"
gltf = "0.16"